### ISSUE TITLE
On netlify the project doesn't work

### ISSUE THREAD

**Issue by SoftDev365** [bstar0406/bstar-web3modal-nft#4]
I have tested my project on local and it works well but on Netlify there are some bug.
My folder name is SencondPage but there was Secondpage. 
Can this be issue for Netlify?

**Comment by bstar0406** [comment]
I have experience in that problem.
Maybe you can see the Secondpage on your git repository compared to your local project has SecondPage.
you can delete it and then repush.
Everything will be fixed!

**Comment by SoftDev365** [comment]
Thanks! It works well.
